### ISSUE TITLE
Check different rustc codegen backends against each other

### ISSUE THREAD

**Issue by bjorn3** [Gankra/abi-checker#4]
This would allow verifying that libraries compiled against one codegen backend (eg llvm) could be linked against those compiled with another codegen backend (eg cranelift). I got a quick implementation over at https://github.com/bjorn3/rustc_codegen_cranelift/issues/1234#issuecomment-1167723143.

**Comment by Gankra** [comment]
Your patch looks decent, the only ??? part is the string you're passing in for the cranelift backend. Is there a more "correct" way to do this? Point to a repo/sha? path? rustup? ..?

**Comment by bjorn3** [comment]
I would like it to be configurable. So for example you could say `--codegen-backend-a=llvm --codegen-backend-b=/path/to/librustc_codegen_cranelift.so` to compare the builtin llvm backend against an external cranelift backend. Not sure what the best commandline interface would be though.

**Comment by Gankra** [comment]
Hmm I think the best way would be to add a `--add-rustc-codegen-backend=my-rustc:path/to/backend` flag which can basically copy the logic for `pairs`:

https://github.com/Gankra/abi-checker/blob/ec12649b6ba0bb73a47d1a91929120d4eedef3d6/src/main.rs#L234

and injects your custom ABI here 

https://github.com/Gankra/abi-checker/blob/ec12649b6ba0bb73a47d1a91929120d4eedef3d6/src/main.rs#L234

Then if there aren't any weird assumptions this breaks, `my-rustc_calls_rustc` will suddenly automagically work.

**Comment by Gankra** [comment]
lmk if you want to tackle this or would prefer me to

**Comment by bjorn3** [comment]
Opened https://github.com/Gankra/abi-checker/pull/5.
